### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by Thor263** [automorphism88/snapraid-btrfs#1]
I'm attempting to use snapraid-btrfs with openmediavault. I have snapper installed and I think I have it configured correctly, but this is what I get when I run 'snapraid-btrfs ls' to verify the setup:

```
Snapper configs found:
data01 /srv/dev-disk-by-label-Disk1/data
data02 /srv/dev-disk-by-label-Disk2/data
snapraid-btrfs: No read permission for  /srv/dev-disk-by-label-Disk1/data/.snapshots  - is SYNC_ACL set in snapper configuration?
```
SYNC_ACL is set to yes:
```
Key                    | Value                            
-----------------------+----------------------------------
ALLOW_GROUPS           |                                  
ALLOW_USERS            |                                  
BACKGROUND_COMPARISON  | no                               
EMPTY_PRE_POST_CLEANUP | no                               
EMPTY_PRE_POST_MIN_AGE | 1800                             
FSTYPE                 | btrfs                            
NUMBER_CLEANUP         | no                               
NUMBER_LIMIT           | 50                               
NUMBER_LIMIT_IMPORTANT | 10                               
NUMBER_MIN_AGE         | 1800                             
QGROUP                 |                                  
SPACE_LIMIT            | 0.5                              
SUBVOLUME              | /srv/dev-disk-by-label-Disk1/data
SYNC_ACL               | yes                              
TIMELINE_CLEANUP       | no                               
TIMELINE_CREATE        | no                               
TIMELINE_LIMIT_DAILY   | 10                               
TIMELINE_LIMIT_HOURLY  | 10                               
TIMELINE_LIMIT_MONTHLY | 10                               
TIMELINE_LIMIT_WEEKLY  | 0                                
TIMELINE_LIMIT_YEARLY  | 10                               
TIMELINE_MIN_AGE       | 1800
```
.snapshots subvolume details:
```
drwxr-x---+ 1 root root    0 Jun 15 07:02 .snapshots

/srv/dev-disk-by-label-Disk1/data/.snapshots
	Name: 			.snapshots
	UUID: 			2f1a0895-3fd9-984a-9f06-e97615063d73
	Parent UUID: 		-
	Received UUID: 		-
	Creation time: 		2019-06-15 07:02:41 -0500
	Subvolume ID: 		6409
	Generation: 		2925
	Gen at creation: 	2802
	Parent ID: 		6404
	Top level ID: 		6404
	Flags: 			-
	Snapshot(s):
```
I've redone the snapper configuration multiple times. Is there anything obvious that I'm missing?

Thanks!

**Comment by Thor263** [comment]
I've figured it out. The version of openmediavault I am using is based on Debian stretch and the version of snapper it installed with apt-get was 0.4.1. When checking the permissions, the `snapper -c data01 ls --disable-used-space` command didn't work:
```
Unknown option '--disable-used-space' for command 'list'.
Try 'snapper --help' for more information.
```
I've since installed the latest snapper (0.8.2) from the strelch-backports repository and the results of `snapraid-btrfs ls` are now much better:
```
Snapper configs found:
data01 /srv/dev-disk-by-label-Disk1/data
data02 /srv/dev-disk-by-label-Disk2/data

data01 /srv/dev-disk-by-label-Disk1/data
 # | Type   | Pre # | Date | User | Cleanup | Description | Userdata
---+--------+-------+------+------+---------+-------------+---------
0  | single |       |      | root |         | current     |         

data02 /srv/dev-disk-by-label-Disk2/data
 # | Type   | Pre # | Date | User | Cleanup | Description | Userdata
---+--------+-------+------+------+---------+-------------+---------
0  | single |       |      | root |         | current     |         
```

This can be closed.

**Comment by automorphism88** [comment]
I went ahead and removed the `--disable-used-space` option for added portability with older snapper versions because it shouldn't really have been necessary, as I don't see any reason to have btrfs quotas enabled on a snapraid data drive. And the fact that with quotas enabled, `snapper ls` can be very slow since it triggers a quota rescan is really a problem with snapper (on my own system, I've actually patched snapper so that it never does this rescan). You should be able to use the latest snapraid-btrfs with older versions of snapper now.

**Comment by automorphism88** [comment]
I actually went ahead and added some code to check the snapper version at runtime and decide accordingly whether or not to use the `--disable-used-space` option (if snapper version is at least 0.6.0). If you still have trouble using the most recent version with older snapper versions, please let me know.

**Comment by MasterCATZ** [comment]
stuck at this point my self atm 

snapraid-btrfs: No read permission for  /mnt/SnapRaidArray/SRD10NA1B9/.snapshots  - is SYNC_ACL set in snapper configuration?
aio@aio:/etc/snapper/configs$ snapper list-configs

aio@aio:/etc/snapper/configs$ snapper -c SRD10NA1B9 get-config
Key                    | Value                        
-----------------------+------------------------------
ALLOW_GROUPS           |                              
ALLOW_USERS            | root aio                     
BACKGROUND_COMPARISON  | no                           
EMPTY_PRE_POST_CLEANUP | yes                          
EMPTY_PRE_POST_MIN_AGE | 1800                         
FSTYPE                 | btrfs                        
NUMBER_CLEANUP         | yes                          
NUMBER_LIMIT           | 50                           
NUMBER_LIMIT_IMPORTANT | 10                           
NUMBER_MIN_AGE         | 1800                         
QGROUP                 |                              
SPACE_LIMIT            | 0.5                          
SUBVOLUME              | /mnt/SnapRaidArray/SRD10NA1B9
SYNC_ACL               | yes                          
TIMELINE_CLEANUP       | yes                          
TIMELINE_CREATE        | yes                          
TIMELINE_LIMIT_DAILY   | 14                           
TIMELINE_LIMIT_HOURLY  | 24                           
TIMELINE_LIMIT_MONTHLY | 12                           
TIMELINE_LIMIT_WEEKLY  | 4                            
TIMELINE_LIMIT_YEARLY  | 2                            
TIMELINE_MIN_AGE       | 1800                         
aio@aio:/etc/snapper/configs$ snapper -version
Unknown global option 'snapper'.
Try 'snapper --help' for more information.
aio@aio:/etc/snapper/configs$ snapper --version
snapper 0.5.4
flags btrfs,lvm,no-ext4,xattrs,rollback,btrfs-quota,no-selinux
aio@aio:/etc/snapper/configs$ 




even wiped all pre existing snapshots 
should I disable snapper and remove /.snapshots folder and try again ?
even using sudo goes no where

aio@aio:/etc/snapper/configs$ sudo btrfs subvolume list /mnt/SnapRaidArray/SRD10NA1B9 
ID 2040 gen 10347 top level 5 path .snapshots
ID 2062 gen 10320 top level 5 path content
