### ISSUE TITLE
Quick guide + missing snapper-config file (its there, snapper knows it)

### ISSUE THREAD

**Issue by zilexa** [automorphism88/snapraid-btrfs#13]
First of all, thank you for this tool and the readme. 
I do wish there was a short quick guide of sorts, just describing the actions (1 per line) one should take when doing a clean, fresh install. Currently everything one has to do to set it up, is spread out over the readme. 

A quick guide: 
1. `sudo apt install snapraid`. Notice the snapraid binary will be stored in /etc/.
1. Download btrfs-snapraid, extract and copy `btrfs-snapraid` to `/etc/` manually (as this is the dir that snapraid installs to by default, via apt install snapraid)
2. `sudo apt install snapper`. 
3. Create snapper-configs for each disk: `sudo snapper -c disk1 create-config /mnt/disks/disk1/`.
4. Create a subvolume on each data disks `sudo btrfs subvolume create /mnt/disks/disk1/.snapraid` which will contain the `snapraid.content` file. If your System OS disk is also a datadisk, create the subvolume in root (`/.snapraid`) and make sure afterwards you give the admin user account ownership instead of root via `sudo chown -R user:user /.snapraid`.
5. Create `/etc/snapraid.conf` file using the example provided by snapraid. (1) Add the path of your data disks and your parity disk. (2) Make sure to add the locations of the content files of each disk `/mnt/yourdisk1/.snapraid/snapraid.content`. (3) You can additionally add /mnt/yourparitydisk/snapraid.content. (4) add `exclude /.snapshots/` to the exclude list.  
6. That should be it. Now run `snapraid check` just to see if there are typos in the conf file. 
7. Now run `snapraid-btrfs ls` to check if you are ready. 

That is what I did. 
But now snapraid and snapraid-btrfs complain about missing content files. Am I good to go (will they be created at first run?) Or should I run `snapraid sync` once just to make sure it creates the `snapraid.content` files?

**Comment by zilexa** [comment]
I dared to simply run the command and discovered an additional step was needed (you did mention it in the readme!)
9. `sudo chown -R user:user /mnt/disks/disk1/.snapraid` for each datadisk after you created the subvolume. 

Now it seems to realise it is the first run (actually second, first one gave me permission errors) run and it is working!
Total data is about 1.2TB so it will take a while.

But there is 1 drive not included. And I have a few questions:

The missing drive:
```
$ snapraid-btrfs sync
Snapper configs found:
disk1 /mnt/disks/disk1
disk2 /mnt/disks/disk2
disk3 /mnt/disks/disk3
```
Why doesn't snapraid-btrfs list my first config here, snapper does see it:
```
$ snapper list-configs
Config | Subvolume       
-------+-----------------
cache  | /mnt/disks/cache
disk1  | /mnt/disks/disk1
disk2  | /mnt/disks/disk2
disk3  | /mnt/disks/disk3
```
And: 
![Screenshot from 2021-01-17 21-35-48](https://user-images.githubusercontent.com/3430004/104855273-11ea9d00-590c-11eb-8b40-021b88a52f22.png)
Why is cache (its just a SSD) missing? it has the path to `/mnt/disks/cache`. 

A few questions:
```
Scanning disk d1...
WARNING! Ignoring mount point '/mnt/disks/cache/.snapraid' because it appears to be in a different device
Scanning disk d2...
WARNING! Ignoring mount point '/mnt/disks/disk1/.snapshots/3/snapshot/.snapraid' because it appears to be in a different device
Scanning disk d3...
WARNING! Ignoring mount point '/mnt/disks/disk2/.snapshots/3/snapshot/.snapraid' because it appears to be in a different device
Scanning disk d4...
WARNING! Ignoring mount point '/mnt/disks/disk3/.snapshots/3/snapshot/.snapraid' because it appears to be in a different device
```
Why do I get this warnings, even if I have:
`exclude /.snapshots/` in my `/etc/snapraid.conf` file? The file is even printed out when I run snapraid-btrfs and I can see it is there. 

Also, can I do anything about this?
```
WARNING! UUID is unsupported for disks: 'd2', 'd3', 'd4'. Not using inodes to detect move operations.
```
Notice `d1` is not mentioned. This is `mnt/disks/cache`, for which I have the snapper-config file `cache` that is not found by snapraid-btrfs.

**Comment by fmoledina** [comment]
> Why is cache (its just a SSD) missing? it has the path to `/mnt/disks/cache`.

Is `/mnt/disks/cache` part of your `/etc/snapraid.conf`? If not, it won't show up under `snapraid-btrfs ls`. You can have snapper manage other volumes that are not part of Snapraid.

**Comment by zilexa** [comment]
it is, "d1 data /mnt/disks/cache":

```
# Example configuration for snapraid

# Defines the file to use as parity storage
# It must NOT be in a data disk
# Format: "parity FILE [,FILE] ..."
parity /mnt/disks/disk4/snapraid.parity

# Defines the files to use as additional parity storage.
# If specified, they enable the multiple failures protection
# from two to six level of parity.
# To enable, uncomment one parity file for each level of extra
# protection required. Start from 2-parity, and follow in order.
# It must NOT be in a data disk
# Format: "X-parity FILE [,FILE] ..."

# Defines the files to use as content list
# You can use multiple specification to store more copies
# You must have least one copy for each parity file plus one. Some more don't hurt
# They can be in the disks used for data, parity or boot,
# but each file must be in a different disk
# Format: "content FILE"
content /.snapraid/snapraid.content
content /mnt/disks/cache/.snapraid/snapraid.content
content /mnt/disks/disk1/.snapraid/snapraid.content
content /mnt/disks/disk2/.snapraid/snapraid.content
content /mnt/disks/disk3/.snapraid/snapraid.content
content /mnt/disks/disk4/snapraid.content

# Defines the data disks to use
# The name and mount point association is relevant for parity, do not change it
# WARNING: Adding here your /home, /var or /tmp disks is NOT a good idea!
# SnapRAID is better suited for files that rarely changes!
# Format: "data DISK_NAME DISK_MOUNT_POINT"
data d1 /mnt/disks/cache/
data d2 /mnt/disks/disk1/
data d3 /mnt/disks/disk2/
data d4 /mnt/disks/disk3/

# Excludes hidden files and directories (uncomment to enable).
#nohidden

# Defines files and directories to exclude
# Remember that all the paths are relative at the mount points
# Format: "exclude FILE"
# Format: "exclude DIR/"
# Format: "exclude /PATH/FILE"
# Format: "exclude /PATH/DIR/"
exclude .snapshots/
exclude *.unrecoverable
exclude /tmp/
exclude /lost+found/
exclude /tmp/
exclude /lost+found/
exclude .AppleDouble
exclude ._AppleDouble
exclude .DS_Store
exclude .Thumbs.db
exclude .fseventsd
exclude .Spotlight-V100
exclude .TemporaryItems
exclude .Trashes
exclude .AppleDB
exclude .err
exclude .bak
exclude .dmp
exclude .dump
exclude .old
exclude .tmp
exclude .temp

# Defines the block size in kibi bytes (1024 bytes) (uncomment to enable).
# WARNING: Changing this value is for experts only!
# Default value is 256 -> 256 kibi bytes -> 262144 bytes
# Format: "blocksize SIZE_IN_KiB"
#blocksize 256

# Defines the hash size in bytes (uncomment to enable).
# WARNING: Changing this value is for experts only!
# Default value is 16 -> 128 bits
# Format: "hashsize SIZE_IN_BYTES"
#hashsize 16

# Automatically save the state when syncing after the specified amount
# of GB processed (uncomment to enable).
# This option is useful to avoid to restart from scratch long 'sync'
# commands interrupted by a machine crash.
# It also improves the recovering if a disk break during a 'sync'.
# Default value is 0, meaning disabled.
# Format: "autosave SIZE_IN_GB"
autosave 150

# Defines the pooling directory where the virtual view of the disk
# array is created using the "pool" command (uncomment to enable).
# The files are not really copied here, but just linked using
# symbolic links.
# This directory must be outside the array.
# Format: "pool DIR"
#pool /pool

# Defines a custom smartctl command to obtain the SMART attributes
# for each disk. This may be required for RAID controllers and for
# some USB disk that cannot be autodetected.
# In the specified options, the "%s" string is replaced by the device name.
# Refers at the smartmontools documentation about the possible options:
# RAID -> https://www.smartmontools.org/wiki/Supported_RAID-Controllers
# USB -> https://www.smartmontools.org/wiki/Supported_USB-Devices
#smartctl d1 -d sat %s
#smartctl d2 -d usbjmicron %s
#smartctl parity -d areca,1/1 /dev/sg0
#smartctl 2-parity -d areca,2/1 /dev/sg0
```

**Comment by fmoledina** [comment]
Ah interesting. That's curious, then.

**Comment by zilexa** [comment]
It's still doing its first sync, ETA 2hrs.
I will do another sync in the morning, see what happens.

**Comment by zilexa** [comment]
Could you please clarify the workaround:
https://github.com/automorphism88/snapraid-btrfs#known-issues

If I just want to do it globally, if I understand correctly all I have to do is a `snapraid sync` and then a `snapraid-btrfs sync`?

**Comment by zilexa** [comment]
Second run did show my cache disk. 
I had renamed all disks in /etc/snapraid.conf from d1-d4 to cache, disk1, disk2 etc. Then I did the 2nd attempt. Now snapraid-btrfs complained no snapper-configs could be found. 
I renamed the disks back to d1-d4 in the .conf file and did a 3rd attempt: now all snapper-configs were found. 

The missing UUID question is the only one I have left.

**Comment by fmoledina** [comment]
I'm not the dev but from what I understand, upstream snapraid uses UUID to help determine explicit move operations rather than considering moves to be a combination of _add_ and _remove_ operations. This allows it to be efficient with parity calculations as the parity is still valid for files that have simply moved, they're just in a different location. This works on the live filesystem even when using BTRFS disks.

With the snapshot, the UUID capability is lost, so tracking explicit _move_ operations is not possible. The workaround suggests that if you have a lot of large move operations, rather than using `snapraid-btrfs` and going through a long parity update procedure for files that are essentially unchanged, it would be worth running native `snapraid sync` on the live filesystem to efficiently update the parity for the large move operation. Subsequently, you would run `snapraid-btrfs sync` update parity using BTRFS snapshots.

**Comment by zilexa** [comment]
I did a snapraid sync again, and snapraid-btrfs again after that, now the UUID message is gone.

Due to unrelated issues, I made very big changes to the data on my datadrive. Is it possible to "start clean" by removing all snapraid.content files, deleting the contents of the .snapshots folder (not sure how) on each disk and formatting the parity drive?

I don't seem to be able to simply delete all the snapshots folders in .snapshots.

**Comment by automorphism88** [comment]
> I'm not the dev but from what I understand, upstream snapraid uses UUID to help determine explicit move operations rather than considering moves to be a combination of _add_ and _remove_ operations. This allows it to be efficient with parity calculations as the parity is still valid for files that have simply moved, they're just in a different location. This works on the live filesystem even when using BTRFS disks.
> 
> With the snapshot, the UUID capability is lost, so tracking explicit _move_ operations is not possible. The workaround suggests that if you have a lot of large move operations, rather than using `snapraid-btrfs` and going through a long parity update procedure for files that are essentially unchanged, it would be worth running native `snapraid sync` on the live filesystem to efficiently update the parity for the large move operation. Subsequently, you would run `snapraid-btrfs sync` update parity using BTRFS snapshots.

This is accurate. When you move/rename files on the same filesystem, you're just updating the metadata, not actually rewriting the file. SnapRAID would like to do the same thing, and update the metadata in the content file to reflect the new path for that file without rewriting the parity, but to do that, it has to recognize that it's the same file in a different location. It does this by using the fact that the inode number doesn't change when you rename a file, but that doesn't work if the filesystem UUID has changed, as in the case of btrfs snapshots.

> Due to unrelated issues, I made very big changes to the data on my datadrive. Is it possible to "start clean" by removing all snapraid.content files, deleting the contents of the .snapshots folder (not sure how) on each disk and formatting the parity drive?

Yes. You can delete all snapshots created by `snapraid-btrfs` by running `snapraid-btrfs cleanup-all`. However, unless "very big changes" means you completely deleted everything and will never want to recover anything that was on your array before, think twice before doing this, because you will lose the ability to recover anything using `snapraid fix` until you regenerate the parity. There's no need to reformat the parity drives or delete the content files no matter how much has changed. And running `snapraid-btrfs cleanup-all` means that you lose the protection offered by `snapraid-btrfs` until you complete a new sync. The `cleanup-all` command is basically an "uninstall" feature.

What I would recommend instead is just doing a normal `snapraid-btrfs sync`, followed by `snapraid-btrfs cleanup`. Even if you have to resync every single block in the array, it won't be any slower than completely nuking the parity/content/snapshots and starting over.

> I don't seem to be able to delete the "current" snapshot of snapper, there is always, for each drive a snapshot "created now" called "current" that can be HUGE and undeletable.

That's not actually a snapshot. The "snapshot" labelled "0" with description "current" refers to the live filesystem, the subvolume you specified when you created the snapper config. That's why it is always there when you create a new snapper configuration. It was already there. It's the subvolume that all the real snapshots are snapshots of.
