### ISSUE TITLE
use_snapshot_fix/--use-filter-disk infinite loop

### ISSUE THREAD

**Issue by Suika** [automorphism88/snapraid-btrfs#2]
Hi, I noticed it some time ago that when `snapraid-btrfs fix` is called with the command `--use-filter-disk`, it will enter and infinite loop since the array also contains the command fix for which there is no option. Rendering "single disk" restore, impossible.

See: 9e1df31da22845303587dba4748751e8c591e49a

**Comment by automorphism88** [comment]
Good catch. Should be fixed by d2a9e6bd86b22750370b28e779b93345311bee4c, which also adds some extra error checking to that function.
